export default function CartItem(req, res) {
  res.status(200).json([
    {
      Id: "e33fcf6a-449c-451a-90b1-7ca5174d9671",
      Code: "1000-0001",
      Name: "Газрын алим кг",
      Color: null,
      Size: null,
      BrandName: null,
      GroupName: "/Алим",
      CategoryName: "Кг үр",
      ListPrice: 720000,
      PriceListName: "Үндсэн үнэ",
      WholeQty: 1,
      QtyPerpackage: 1,
      WeightPerPackage: 1,
      Volume: 0,
      QtyPackage: 1,
      Vendor: null,
      Manufacturer: null,
      Link: null,
      Images: null,
    },
    {
      Id: "86ac3ea5-6969-4e48-92af-7f736663e21e",
      Code: "1000-0005",
      Name: "Салад навч кг ногоон",
      Color: null,
      Size: null,
      BrandName: null,
      GroupName: "/Навч",
      CategoryName: "Кг үр",
      ListPrice: 270000,
      PriceListName: "Үндсэн үнэ",
      WholeQty: 1,
      QtyPerpackage: 1,
      WeightPerPackage: 1,
      Volume: 0,
      QtyPackage: 1,
      Vendor: null,
      Manufacturer: null,
      Link: null,
      Images: null,
    },
    {
      Id: "775ecc99-51b3-49af-b0b4-4ac4ee9b9ff2",
      Code: "1000-0006",
      Name: "Укроп кг",
      Color: null,
      Size: null,
      BrandName: null,
      GroupName: "/Укроп",
      CategoryName: "Кг үр",
      ListPrice: 87000,
      PriceListName: "Үндсэн үнэ",
      WholeQty: 1,
      QtyPerpackage: 1,
      WeightPerPackage: 1,
      Volume: 0,
      QtyPackage: 1,
      Vendor: null,
      Manufacturer: null,
      Link: null,
      Images: null,
    },
  ]);
}
